apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml

configMapGenerator:
- name: tmc-event-streamer
  files:
  - event_stream_service_call.py
  literals:
  - tmc_url=https://< YOUR ORG HERE >.tmc.cloud.vmware.com
generatorOptions:
  disableNameSuffixHash: true